version: "3.11"

services:
  lexyserver:
    build:
      context: ./
      dockerfile: docker/server/Dockerfile
    hostname: lexy_server
    container_name: lexy-server
    depends_on:
      - db_postgres
    ports:
      - "9900:9900"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lexy
      - POSTGRES_HOST=db_postgres
      - CELERY_BROKER_URL=amqp://guest:guest@queue:5672//
      - CELERY_RESULT_BACKEND=db+postgresql://postgres:postgres@db_postgres/lexy
    volumes:
      - ./:/home/app
    networks:
      - lexy-net

  db_postgres:
    hostname: db_postgres
    container_name: lexy-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lexy
      - POSTGRES_TEST_DB=lexy_tests
    ports:
      - "5432:5432"
    build:
        context: ./
        dockerfile: docker/postgres/Dockerfile
    volumes:
      - db-postgres:/var/lib/postgresql/data
    networks:
      - lexy-net

  queue:
    image: rabbitmq:3.9.10-management
    hostname: queue
    container_name: lexy-queue
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - lexy-net

  flower:
    image: mher/flower
    hostname: flower
    container_name: lexy-flower
    restart: always
    ports:
      - "5556:5555"
    command: celery --broker=amqp://guest:guest@queue:5672// flower -A lexy.main.celery --broker_api=http://guest:guest@queue:15672/api/vhost
    depends_on:
      - lexyserver
      - queue
      - lexyworker
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@queue:5672//
      - CELERY_RESULT_BACKEND=db+postgresql://postgres:postgres@db_postgres/lexy
      - CELERY_BROKER_API_URL=http://guest:guest@queue:15672/api/vhost
      - C_FORCE_ROOT=true
      - FLOWER_UNAUTHENTICATED_API=true
    networks:
      - lexy-net

  lexyworker:
    build:
      context: ./
      dockerfile: docker/worker/Dockerfile
    hostname: celeryworker
    container_name: lexy-celeryworker
    command: celery -A lexy.main.celery worker --loglevel=info -Q celery -c 4
    depends_on:
      - lexyserver
      - queue
    restart: always
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@queue:5672//
      - CELERY_BROKER_API_URL=http://guest:guest@queue:15672/api/vhost
      - CELERY_RESULT_BACKEND=db+postgresql://postgres:postgres@db_postgres/lexy
      - C_FORCE_ROOT=true
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lexy
      - POSTGRES_HOST=db_postgres
    volumes:
      - ./:/home/app
    networks:
      - lexy-net


volumes:
  db-postgres:
    driver: local

networks:
  lexy-net:
    external: false
