name: lx-test

services:
  lexyserver:
    build:
      args:
        ENVIRONMENT: test
    env_file:
      - .env.test
    environment:
      - ENVIRONMENT=test
      - OPENAI_API_KEY
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_DEFAULT_REGION
      - AWS_REGION

  lexyworker:
    build:
      args:
        ENVIRONMENT: test
    env_file:
      - .env.test
    environment:
      - ENVIRONMENT=test
