### Send POST request with json body
POST http://localhost:9900/documents
Content-Type: application/json

[
  {
    "content": "This is my very first document and I'm very excited about it!"
  }
]

###
