"""init

Revision ID: 86fb79fd96f8
Revises: 
Create Date: 2023-12-20 18:06:29.251724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # ADDED
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86fb79fd96f8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ADDED: update existing rows to set the config column to an empty dictionary
    op.execute("UPDATE collections SET config = '{\"store_files\": true, \"generate_thumbnails\": true}'::jsonb "
               "WHERE config IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collections', 'config')
    # ### end Alembic commands ###
