"""Drop embeddings table

Revision ID: e0e61caaf942
Revises: 93fff08ca05d
Create Date: 2024-01-09 15:13:26.153607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # ADDED
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0e61caaf942'
down_revision: Union[str, None] = '93fff08ca05d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_embeddings_document_id', table_name='embeddings')
    op.drop_index('ix_embeddings_embedding_hnsw', table_name='embeddings', postgresql_with={'dims': '384', 'm': '8', 'efconstruction': '16', 'efsearch': '16'}, postgresql_using='hnsw')
    op.drop_index('ix_embeddings_embedding_id', table_name='embeddings')
    op.drop_table('embeddings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embeddings',
    sa.Column('embedding', postgresql.ARRAY(sa.REAL()), autoincrement=False, nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('document_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('custom_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('embedding_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('task_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], name='embeddings_document_id_fkey'),
    sa.PrimaryKeyConstraint('embedding_id', name='embeddings_pkey')
    )
    op.create_index('ix_embeddings_embedding_id', 'embeddings', ['embedding_id'], unique=False)
    op.create_index('ix_embeddings_embedding_hnsw', 'embeddings', ['embedding'], unique=False, postgresql_with={'dims': '384', 'm': '8', 'efconstruction': '16', 'efsearch': '16'}, postgresql_using='hnsw')
    op.create_index('ix_embeddings_document_id', 'embeddings', ['document_id'], unique=False)
    # ### end Alembic commands ###
