site_name: Lexy AI
site_description: Lexy is a data platform for building AI applications.
site_url: https://getlexy.com
docs_dir: docs
site_dir: site

repo_url: https://github.com/lexy-ai/lexy
repo_name: lexy-ai/lexy

theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.indexes
  favicon: assets/public/favicon.ico
  icon:
    repo: material/github
  logo: assets/public/logo.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      default_handler: python
      handlers:
        python:
          paths:
            - ../lexy
            - ../sdk-python
          options:
            show_root_heading: true
            inherited_members: true
            signature_crossrefs: true
            filters: ["!^_"]
            show_if_no_docstring: false
            show_inherited_class_attributes: true
            show_inherited_class_methods: true
            show_inherited_docstrings: true
            extensions:
              - griffe_fieldz: {include_inherited: false}
  - swagger-ui-tag:
      supportedSubmitMethods: []

nav:
  - Home: index.md
  - Installation: installation.md
  - Quickstart: quickstart.md
  - Tutorials:
    - tutorials/index.md
    - Retrieval Augmented Generation (RAG): tutorials/basic-rag.md
    - Multimodal image search: tutorials/multimodal-image-search.md
    - Custom transformers: tutorials/custom-transformers.md
    - Document filters: tutorials/document-filters.md
    - Structured data extraction: tutorials/structured-data-extraction.md
  - REST API: reference/rest-api/index.md
  - Python SDK:
    - Binding: reference/lexy_py/binding.md
    - Client: reference/lexy_py/client.md
    - Collection: reference/lexy_py/collection.md
    - Document: reference/lexy_py/document.md
    - Filters: reference/lexy_py/filters.md
    - Index: reference/lexy_py/indexes.md
    - Transformer: reference/lexy_py/transformer.md
  - Contributing: contributing.md
  - FAQ: faq.md

extra:
  generator: false
  analytics:
    provider: google
    property: G-GXKGDFL4B1
