site_name: Lexy AI
site_description: Lexy is a data platform for building AI applications.
site_url: https://getlexy.com
docs_dir: docs
site_dir: site

repo_url: https://github.com/lexy-ai/lexy
repo_name: lexy-ai/lexy

theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.indexes
  favicon: assets/public/favicon.ico
  icon:
    repo: material/github
  logo: assets/public/logo.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - encryptcontent:
      title_prefix: ''
      password_button: true
      password_button_text: 'ENTER'
      password_inventory:
        _global:
          lexy: !ENV [MKDOCS_ENCRYPT_PW_LEXY, 'guest']
          lexy_trial_partner1: !ENV [MKDOCS_ENCRYPT_PW_PARTNER1, 'lexypartner1']
          lexy_trial_partner2: !ENV [MKDOCS_ENCRYPT_PW_PARTNER2, 'lexypartner2']
          lexy_trial_partner3: !ENV [MKDOCS_ENCRYPT_PW_PARTNER3, 'lexypartner3']
      encrypted_something:
        md-header__inner: [ nav, class ] #Header
        md-footer__inner: [ nav, class ] #Footer
        md-nav: [ nav, class ] #Menu and toc
      remember_password: true
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      default_handler: python
      handlers:
        python:
          paths:
            - ../lexy
            - ../sdk-python
          options:
            show_root_heading: true
            inherited_members: true
            signature_crossrefs: true
            filters: ["!^_"]
            show_if_no_docstring: false
            show_inherited_class_attributes: true
            show_inherited_class_methods: true
            show_inherited_docstrings: true

nav:
  - Home: index.md
  - Installation: installation.md
  - Quickstart: quickstart.md
  - Tutorials:
    - tutorials/index.md
    - Basic RAG using Lexy: tutorials/basic-rag.md
    - Multimodal image search: tutorials/multimodal-image-search.md
    - Custom transformers: tutorials/custom-transformers.md
    - Document filters: tutorials/document-filters.md
  - Lexy API:
    - Overview: reference/lexy_api/overview.md
  - Python SDK:
    - Binding: reference/lexy_py/binding.md
    - Client: reference/lexy_py/client.md
    - Collection: reference/lexy_py/collection.md
    - Document: reference/lexy_py/document.md
    - Filters: reference/lexy_py/filters.md
    - Index: reference/lexy_py/indexes.md
    - Transformer: reference/lexy_py/transformer.md
  - Contributing: contributing.md
  - FAQ: faq.md

extra:
  generator: false
  analytics:
    provider: google
    property: G-GXKGDFL4B1
