name: Build and Push Docker Images

on:
  push:
    branches:
#      - main
      - rs/test-gh-actions

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_LEXY_SERVER: ghcr.io/lexy-ai/lexy/lexy-server
  IMAGE_NAME_LEXY_WORKER: ghcr.io/lexy-ai/lexy/lexy-worker
  IMAGE_NAME_LEXY_POSTGRES: ghcr.io/lexy-ai/lexy/lexy-postgres

jobs:
  build-and-push:

    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
    
    steps:

      - name: List huge unnecessary tools folder
        run: tree -L 2 /opt/hostedtoolcache
        
      - name: Size of huge unnecessary tools folder
        run: du -sh /opt/hostedtoolcache/*/* | sort -h -r

      - name: Free disk space
        run: df -h

      - name: Other stuff
        run: |
          which python
          which python3
          which pip
          python --version
        
#      - name: Delete huge unnecessary tools folder
#       run: rm -rf /opt/hostedtoolcache

      - name: Delete huge unnecessary tools folder
        run: |
          rm -rf /opt/hostedtoolcache/CodeQL
          df -h

      - name: Check build context
        run: |
          pwd
          ls -lah ./
          du -sh ./* | sort -h -r

      - name: Size of py packages
        run: |
          export PYSITE=$(python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")
          du -sh $PYSITE/* | sort -h -r

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Lexy Server image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./docker/server/Dockerfile
          build-args: ENVIRONMENT=development
          labels: |
            org.opencontainers.image.source=https://github.com/lexy-ai/lexy
            org.opencontainers.image.title=Lexy Server
          push: true
          tags: ${{ env.IMAGE_NAME_LEXY_SERVER }}:latest

      - name: Free disk space after lexy server
        run: df -h

      - name: Check build context after lexy server
        run: |
          pwd
          ls -lah ./
          du -sh ./* | sort -h -r

      - name: Size of py packages after lexy server
        run: |
          export PYSITE=$(python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")
          du -sh $PYSITE/* | sort -h -r

      - name: Build and push Lexy Worker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./docker/worker/Dockerfile
          build-args: ENVIRONMENT=development
          labels: |
            org.opencontainers.image.source=https://github.com/lexy-ai/lexy
            org.opencontainers.image.title=Lexy Worker
          push: true
          tags: ${{ env.IMAGE_NAME_LEXY_WORKER }}:latest

      - name: Free disk space after lexy worker
        run: df -h

      - name: Check build context after lexy worker
        run: |
          pwd
          ls -lah ./
          du -sh ./* | sort -h -r

      - name: Build and push Lexy Postgres image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./docker/postgres/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME_LEXY_POSTGRES }}:latest
