name: Build and Push Docker Images

on:
  push:
    branches:
#      - main
      - rs/test-gh-actions

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_LEXY_SERVER: ${REGISTRY}/lexy-ai/lexy/lexy-server
  IMAGE_NAME_LEXY_WORKER: ${REGISTRY}/lexy-ai/lexy/lexy-worker
  IMAGE_NAME_LEXY_POSTGRES: ${REGISTRY}/lexy-ai/lexy/lexy-postgres

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Lexy Server image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./docker/server/Dockerfile
          build-args: ENVIRONMENT=development
          labels: |
            org.opencontainers.image.source=https://github.com/lexy-ai/lexy
            org.opencontainers.image.title=Lexy Server
          push: true
          tags: ${{ env.IMAGE_NAME_LEXY_SERVER }}:latest

      - name: Build and push Lexy Worker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./docker/worker/Dockerfile
          build-args: ENVIRONMENT=development
          labels: |
            org.opencontainers.image.source=https://github.com/lexy-ai/lexy
            org.opencontainers.image.title=Lexy Worker
          push: true
          tags: ${{ env.IMAGE_NAME_LEXY_WORKER }}:latest

      - name: Build and push Lexy Postgres image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./docker/postgres/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME_LEXY_POSTGRES }}:latest
