name: Build and Push Docker Images

on:
  push:
    branches:
#      - main
      - rs-bugfix-test-celery-worker
    tags:
      - v*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_LEXY_SERVER: ghcr.io/lexy-ai/lexy/lx-server
  IMAGE_NAME_LEXY_WORKER: ghcr.io/lexy-ai/lexy/lx-worker
  IMAGE_NAME_LEXY_POSTGRES: ghcr.io/lexy-ai/lexy/lx-postgres

permissions:
  contents: read
  packages: write

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/arm64
          - linux/amd64

    steps:

      - name: Python stuff
        run: |
          which python
          which python3
          which pip
          python --version

      - name: Free disk space
        run: df -h

      - name: List huge unnecessary tools folder
        run: |
          tree -L 2 /opt/hostedtoolcache
          du -sh /opt/hostedtoolcache/*/* | sort -h -r

      - name: Delete huge unnecessary tools folder
        run: |
          rm -rf /opt/hostedtoolcache
          df -h

      - name: Prepare platform format
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV 

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check build context
        run: |
          pwd
          ls -lah .
          tree -L 2 .

      # Add support for more platforms with QEMU
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Currently not being used
      - name: Metadata for all images
        id: meta-all
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.IMAGE_NAME_LEXY_SERVER }}
            ${{ env.IMAGE_NAME_LEXY_WORKER }}
            ${{ env.IMAGE_NAME_LEXY_POSTGRES }}
          labels: |
            org.opencontainers.image.vendor=Lexy AI
          flavor: |
            latest=auto
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index

      ### Lexy Server ###

      - name: Metadata for server
        id: meta-server
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME_LEXY_SERVER }}
          labels: |
            org.opencontainers.image.title=Lexy Server
            org.opencontainers.image.description=Lexy API Server
            org.opencontainers.image.vendor=Lexy AI
          annotations: |
            org.opencontainers.image.title=Lexy Server
            org.opencontainers.image.description=Lexy API Server
            org.opencontainers.image.vendor=Lexy AI

      - name: Build and push server by digest
        id: build-server
        uses: docker/build-push-action@v5
        with:
          context: ./
          platforms: ${{ matrix.platform }}
          file: ./docker/server/Dockerfile
          build-args: ENVIRONMENT=production
          provenance: false  # Avoid "unknown/unknown" arch (https://github.com/docker/build-push-action/issues/820)
          labels: ${{ steps.meta-server.outputs.labels }}
          annotations: ${{ steps.meta-server.outputs.annotations }}
          outputs: type=image,name=${{ env.IMAGE_NAME_LEXY_SERVER }},push-by-digest=true,name-canonical=true,push=true

      - name: Export server digest
        run: |
          mkdir -p /tmp/digests/server
          digest="${{ steps.build-server.outputs.digest }}"
          touch "/tmp/digests/server/${digest#sha256:}"          

      - name: Upload server digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-server-${{ env.PLATFORM_PAIR }}
          path: /tmp/digests/server/*
          if-no-files-found: error
          retention-days: 1

      ### Lexy Worker ###
      
      - name: Metadata for worker
        id: meta-worker
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME_LEXY_WORKER }}
          labels: |
            org.opencontainers.image.title=Lexy Worker
            org.opencontainers.image.description=Lexy Worker Instance
            org.opencontainers.image.vendor=Lexy AI
          annotations: |
            org.opencontainers.image.title=Lexy Worker
            org.opencontainers.image.description=Lexy Worker Instance
            org.opencontainers.image.vendor=Lexy AI

      - name: Build and push worker by digest
        id: build-worker
        uses: docker/build-push-action@v5
        with:
          context: ./
          platforms: ${{ matrix.platform }}
          file: ./docker/worker/Dockerfile
          build-args: ENVIRONMENT=production
          provenance: false  # Avoid "unknown/unknown" arch (https://github.com/docker/build-push-action/issues/820)
          labels: ${{ steps.meta-worker.outputs.labels }}
          annotations: ${{ steps.meta-worker.outputs.annotations }}
          outputs: type=image,name=${{ env.IMAGE_NAME_LEXY_WORKER }},push-by-digest=true,name-canonical=true,push=true

      - name: Export worker digest
        run: |
          mkdir -p /tmp/digests/worker
          digest="${{ steps.build-worker.outputs.digest }}"
          touch "/tmp/digests/worker/${digest#sha256:}"          

      - name: Upload worker digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-worker-${{ env.PLATFORM_PAIR }}
          path: /tmp/digests/worker/*
          if-no-files-found: error
          retention-days: 1

      ### Lexy Postgres ###
      
      - name: Metadata for postgres
        id: meta-postgres
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME_LEXY_POSTGRES }}
          labels: |
            org.opencontainers.image.title=Lexy Postgres
            org.opencontainers.image.description=Lexy Postgres Database
            org.opencontainers.image.vendor=Lexy AI
          annotations: |
            org.opencontainers.image.title=Lexy Postgres
            org.opencontainers.image.description=Lexy Postgres Database
            org.opencontainers.image.vendor=Lexy AI

      - name: Build and push postgres by digest
        id: build-postgres
        uses: docker/build-push-action@v5
        with:
          context: ./
          platforms: ${{ matrix.platform }}
          file: ./docker/postgres/Dockerfile
          provenance: false  # Avoid "unknown/unknown" arch (https://github.com/docker/build-push-action/issues/820)
          labels: ${{ steps.meta-postgres.outputs.labels }}
          annotations: ${{ steps.meta-postgres.outputs.annotations }}
          outputs: type=image,name=${{ env.IMAGE_NAME_LEXY_POSTGRES }},push-by-digest=true,name-canonical=true,push=true

      - name: Export postgres digest
        run: |
          mkdir -p /tmp/digests/postgres
          digest="${{ steps.build-postgres.outputs.digest }}"
          touch "/tmp/digests/postgres/${digest#sha256:}"          

      - name: Upload postgres digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-postgres-${{ env.PLATFORM_PAIR }}
          path: /tmp/digests/postgres/*
          if-no-files-found: error
          retention-days: 1

  create-manifests:
    runs-on: ubuntu-latest
    needs:
      - build-and-push
    steps:

      - name: Download server digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/digests/server
          pattern: digests-server-*
          merge-multiple: true

      - name: Download worker digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/digests/worker
          pattern: digests-worker-*
          merge-multiple: true

      - name: Download postgres digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/digests/postgres
          pattern: digests-postgres-*
          merge-multiple: true

      - name: List all digests
        run: ls -R /tmp/digests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      ### Manifest for Lexy Server ###

      - name: Docker meta for Lexy server
        id: meta-lx-server
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME_LEXY_SERVER }}
          # labels: |
          #   org.opencontainers.image.title=Lexy Server
          #   org.opencontainers.image.description=Lexy API Server 
          #   org.opencontainers.image.vendor=Lexy AI

      - name: Metadata check for server
        run: |
          echo "$DOCKER_METADATA_OUTPUT_JSON"
          echo "${{ steps.meta-lx-server.outputs.json }}"

      - name: Create server manifest and push
        working-directory: /tmp/digests/server
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.IMAGE_NAME_LEXY_SERVER }}@sha256:%s ' *)          

      - name: Inspect server image
        run: |
          docker buildx imagetools inspect ${{ env.IMAGE_NAME_LEXY_SERVER }}:${{ steps.meta-lx-server.outputs.version }}
          docker buildx imagetools inspect ${{ env.IMAGE_NAME_LEXY_SERVER }}:${{ steps.meta-lx-server.outputs.version }} --format "{{json .Image}}"

      ### Manifest for Lexy Worker ###

      - name: Docker meta for Lexy worker
        id: meta-lx-worker
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME_LEXY_WORKER }}
          # labels: |
          #   org.opencontainers.image.title=Lexy Worker
          #   org.opencontainers.image.description=Lexy Worker Instance 
          #   org.opencontainers.image.vendor=Lexy AI

      - name: Metadata check for worker
        run: |
          echo "$DOCKER_METADATA_OUTPUT_JSON"
          echo "${{ steps.meta-lx-worker.outputs.json }}"

      - name: Create worker manifest and push
        working-directory: /tmp/digests/worker
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.IMAGE_NAME_LEXY_WORKER }}@sha256:%s ' *)          

      - name: Inspect worker image
        run: |
          docker buildx imagetools inspect ${{ env.IMAGE_NAME_LEXY_WORKER }}:${{ steps.meta-lx-worker.outputs.version }}
          docker buildx imagetools inspect ${{ env.IMAGE_NAME_LEXY_WORKER }}:${{ steps.meta-lx-worker.outputs.version }} --format "{{json .Image}}"

      ### Manifest for Lexy Postgres ###

      - name: Docker meta for Lexy postgres
        id: meta-lx-postgres
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME_LEXY_POSTGRES }}
          # labels: |
          #   org.opencontainers.image.title=Lexy Postgres
          #   org.opencontainers.image.description=Lexy Postgres Database 
          #   org.opencontainers.image.vendor=Lexy AI

      - name: Metadata check for postgres
        run: |
          echo "$DOCKER_METADATA_OUTPUT_JSON"
          echo "${{ steps.meta-lx-postgres.outputs.json }}"

      - name: Create postgres manifest and push
        working-directory: /tmp/digests/postgres
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.IMAGE_NAME_LEXY_POSTGRES }}@sha256:%s ' *)          

      - name: Inspect postgres image
        run: |
          docker buildx imagetools inspect ${{ env.IMAGE_NAME_LEXY_POSTGRES }}:${{ steps.meta-lx-postgres.outputs.version }}
          docker buildx imagetools inspect ${{ env.IMAGE_NAME_LEXY_POSTGRES }}:${{ steps.meta-lx-postgres.outputs.version }} --format "{{json .Image}}"
