name: Run tests

on:
  push:
    branches:
      - rs/run-tests-on-gh
  pull_request:
    branches:
      - main

permissions:
    contents: read

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Free disk space
        run: df -h

      - name: List huge unnecessary tools folder
        run: |
          tree -L 2 /opt/hostedtoolcache
          du -sh /opt/hostedtoolcache/*/* | sort -h -r

      - name: Delete huge unnecessary tools folder
        run: |
          rm -rf /opt/hostedtoolcache
          df -h

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check build context
        run: |
          pwd
          ls -lah .
          tree -L 2 .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

#      - name: Build server image
#        uses: docker/build-push-action@v5
#        with:
#          context: .
#          file: docker/server/Dockerfile
#          platforms: linux/amd64,linux/arm64
#          push: false

      - name: Build the stack
        run: |
          touch .env
          touch .env.test
          # echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env.test
          # echo "PIPELINE_DIR=./pipelines" >> .env.test
          docker compose -f docker-compose.yaml -f docker-compose.test.yaml config
          docker compose -f docker-compose.yaml -f docker-compose.test.yaml up --build -d
          docker compose -f docker-compose.yaml -f docker-compose.test.yaml ps

      - name: Run tests
        run: |
          docker compose -f docker-compose.yaml -f docker-compose.test.yaml exec lexyserver pytest lexy_tests
          docker compose -f docker-compose.yaml -f docker-compose.test.yaml exec lexyserver pytest sdk-python

      - name: Tear down the stack
        run: |
          docker compose -f docker-compose.yaml -f docker-compose.test.yaml down
